#!/usr/bin/env bash
# Stamp a build version into the static site.
#
#   bash scripts/stamp-version.sh [outdir]
#
# Copies the repo (minus git and CI files) to <outdir> (default _site),
# writes <outdir>/version.js from git metadata, and injects the script tag
# into every *.dc.html so the footer appears on each page. Nothing in the
# source tree is modified, so a re-exported design keeps working unchanged.

set -euo pipefail

out="${1:-_site}"
root="$(cd "$(dirname "$0")/.." && pwd)"

build="$(git -C "$root" rev-list --count HEAD)"
sha="$(git -C "$root" rev-parse --short HEAD)"
iso="$(git -C "$root" log -1 --format=%cI)"
date="$(TZ=America/Chicago git -C "$root" log -1 --format=%cd --date=format-local:%Y-%m-%d)"

rm -rf "$out"
mkdir -p "$out"
rsync -a --exclude .git --exclude .github --exclude scripts --exclude "$out" "$root/" "$out/"

# Cache-bust every script the page pulls. GitHub Pages sends
# `cache-control: max-age=600` on these files, so without a per-build URL a
# browser that opened the site in the last ten minutes keeps running the
# previous build's JavaScript against the new markup - which is how a fixed
# bug can still look broken to the person you sent the link to.
#
# Only the copy in $out is rewritten; the source tree stays clean, so a fresh
# Claude Design export drops in without carrying stamps from an old build.
find "$out" -maxdepth 1 \( -name '*.js' -o -name '*.html' \) -print0 |
  while IFS= read -r -d '' f; do
    perl -pi -e "s#(\./(?:naas-[a-z0-9-]+|support)\.js)(?!\?)#\$1?v=${sha}#g" "$f"
  done

cat > "$out/version.js" <<EOF
// Generated by scripts/stamp-version.sh at deploy time. Do not edit or commit.
(function () {
  var v = { build: ${build}, sha: "${sha}", date: "${date}", iso: "${iso}" };
  window.__naasVersion = v;
  function mount() {
    if (document.getElementById('naas-version')) return;
    // A page that prints the build itself (the storefront's title row) opts out of the floating pill.
    if (document.body && document.body.dataset.versionPill === 'off') return;
    var el = document.createElement('div');
    el.id = 'naas-version';
    el.setAttribute('role', 'contentinfo');
    el.setAttribute('aria-label', 'Build ' + v.build + ', ' + v.date);
    el.title = 'Build ' + v.build + ' · ' + v.sha + ' · ' + v.iso;
    el.textContent = 'v' + v.build + ' · ' + v.date;
    el.style.cssText = 'position:fixed;left:50%;bottom:8px;transform:translateX(-50%);z-index:60;' +
      'padding:3px 10px;border-radius:9999px;font:11px/16px "Aleck Sans","ATT Aleck Sans",system-ui,sans-serif;' +
      'letter-spacing:.02em;color:rgba(128,128,128,.95);background:rgba(128,128,128,.14);' +
      'backdrop-filter:blur(6px);-webkit-backdrop-filter:blur(6px);white-space:nowrap;cursor:default;user-select:none';
    document.body.appendChild(el);
  }
  if (document.body) mount(); else document.addEventListener('DOMContentLoaded', mount);
})();
EOF

for f in "$out"/*.dc.html; do
  [ -f "$f" ] || continue
  if ! grep -q 'version\.js' "$f"; then
    perl -0pi -e "s#</body>#<script src=\"./version.js?v=${sha}\" defer></script>\n</body>#" "$f"
  fi
done

echo "stamped build ${build} (${sha}, ${date}) into ${out}/"
echo "cache-busted $(grep -ho "?v=${sha}" "$out"/*.js "$out"/*.html | wc -l | tr -d " ") script references"
